name: Tests
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  flake8:
    name: flake8 check
    runs-on: ubuntu-22.04
    steps:
      - name: Flake8 Code Check
        uses: dizi-izi-plan/dizi-izi-backend/.github/actions/flake8@main

  unit_tests:
    name: unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash
      - name: Run unit tests
        run: python manage.py test
        shell: bash
